baseURL = "http://ltratcliff.com/"
languageCode = "en-us"
title = "TR"
theme="ananke"

SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true
enableEmoji = true


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = "Tom Ratcliff"
  favicon = "images/logo.png"
  #site_logo = "images/logo.png"
  description = "A Blog on Software Experiences, Troubleshooting, Fix Actions and More!"
  facebook = "https://facebook.com/ltratcliff"
  twitter = "https://twitter.com/ltratcliff"
  instagram = ""
  youtube = ""
  github = "https://github.com/ltratcliff/"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/ltratcliff/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = "https://ltratcliff.com/index.xml"
  background_color_class = "bg-black"
  #body_classes = "avenir bg-moon-gray"
  featured_image = "/images/sugarshack.jpg"
  recent_posts_number = 3
