baseURL = "http://ltratcliff.com/"
languageCode = "en-us"
title = "TR"
theme="ananke"

SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true
enableEmoji = true

#googleAnalytics = "G-H9T1HNDM5K"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  googleAnalyticsID = "G-H9T1HNDM5K"
  author = "Tom Ratcliff"
  favicon = "images/logo.png"
  #site_logo = "images/logo.png"
  description = "Blog on Software and Hardware Experiences."
  facebook = "https://facebook.com/ltratcliff"
  twitter = "https://twitter.com/ltratcliff"
  instagram = ""
  youtube = ""
  github = "https://github.com/ltratcliff/"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/ltratcliff/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = "https://ltratcliff.com/index.xml"
  background_color_class = "bg-black"
  #body_classes = "avenir bg-moon-gray"
  featured_image = "/images/sugarshack.jpg"
  recent_posts_number = 3

[markup.goldmark.renderer]
  unsafe = true



[services]
  [services.disqus]
    shortname = 'disqus_1LO0YJVLTk'


