baseURL = "http://ltratcliff.com/"
languageCode = "en-us"
title = "TR"
theme="ananke"

SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true
enableEmoji = true

#googleAnalytics = "G-H9T1HNDM5K"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  googleAnalyticsID = "G-H9T1HNDM5K"
  author = "Tom Ratcliff"
  favicon = "images/logo.png"
  #site_logo = "images/logo.png"
  description = "Blog on Software and Hardware Experiences."
  stackoverflow = ""
  rss = "https://ltratcliff.com/index.xml"
  background_color_class = "bg-black"
  #body_classes = "avenir bg-moon-gray"
  featured_image = "/images/sugarshack.jpg"
  recent_posts_number = 3

[params.ananke.social.follow]
  new_window_icon = true
  networks = [
    "facebook",
    "twitter",
    "linkedin",
    "stackoverflow",
    "github",
    "rss"
  ]

[params.ananke.social.facebook]
username = "ltratcliff"
[params.ananke.social.twitter]
username = "ltratcliff"
[params.ananke.social.linkedin]
username = "ltratcliff"
[params.ananke.social.stackoverflow]
username = "4176724"
[params.ananke.social.github]
username = "ltratcliff"
[params.ananke.social.rss]
profilelink = "index.xml"

[params.ananke.social.share]
icons = true
sharetext = true
networks = [
  "email",
  "facebook",
  "twitter",
  "linkedin"
]


[markup.goldmark.renderer]
  unsafe = true



[services]
  [services.disqus]
    shortname = 'ltratcliff-com'


