name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      #(Optional) If you have the theme added as submodule and Update theme step(next step) is not working then delete themes directory
      #- name: Clone theme
      #  run: git submodule add --depth=1 https://github.com/theNewDynamic/gohugo-theme-ananke.git themes/ananke 

      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        run: git submodule update --init --recursive

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.91.2"
          extended: true

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: HUGO_ENV=production hugo 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: ltratcliff/ltratcliff.github.io
          publish_dir: ./public
          #   keep_files: true
          user_name: ltratcliff
          user_email: ltratcliff@gmail.com
          publish_branch: main
          cname: ltratcliff.com

